// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RSSI_Nuro.Data;

#nullable disable

namespace RSSI_Nuro.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240901181226_DataRelationInit")]
    partial class DataRelationInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RSSI_Nuro.Models.ArchiveDataModel", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<double>("Bt")
                        .HasColumnType("float");

                    b.Property<double>("BxGSM")
                        .HasColumnType("float");

                    b.Property<double>("ByGSM")
                        .HasColumnType("float");

                    b.Property<double>("BzGSM")
                        .HasColumnType("float");

                    b.Property<double>("Declination")
                        .HasColumnType("float");

                    b.Property<double>("Density")
                        .HasColumnType("float");

                    b.Property<double>("East")
                        .HasColumnType("float");

                    b.Property<double>("Horizontal")
                        .HasColumnType("float");

                    b.Property<double>("Inclination")
                        .HasColumnType("float");

                    b.Property<double>("Intensity")
                        .HasColumnType("float");

                    b.Property<double>("North")
                        .HasColumnType("float");

                    b.Property<double>("Speed")
                        .HasColumnType("float");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<double>("Vertical")
                        .HasColumnType("float");

                    b.HasKey("Timestamp");

                    b.ToTable("ArchiveRecords");
                });

            modelBuilder.Entity("RSSI_Nuro.Models.ReconDataModel", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<float>("Bt")
                        .HasColumnType("real");

                    b.Property<float>("BxGSM")
                        .HasColumnType("real");

                    b.Property<float>("ByGSM")
                        .HasColumnType("real");

                    b.Property<float>("BzGSM")
                        .HasColumnType("real");

                    b.Property<float>("Density")
                        .HasColumnType("real");

                    b.Property<float>("Speed")
                        .HasColumnType("real");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.HasKey("Timestamp");

                    b.ToTable("ReconnectionRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
